use indexmap::IndexMap;
use once_cell::sync::Lazy;
use serde_json::Number;

use super::types;

pub static UI_CONFIGURATION: Lazy<types::UI> = Lazy::new(|| types::UI {
    name: String::from("Seyuna"),
    slogan: String::from("Another cool Seyuna app."),
    theme: types::Theme {
        colors: IndexMap::from([
            ("alpha".to_string(), Number::from(0)),
            ("beta".to_string(), Number::from(15)),
            ("gamma".to_string(), Number::from(30)),
            ("delta".to_string(), Number::from(45)),
            ("epsilon".to_string(), Number::from(60)),
            ("zeta".to_string(), Number::from(75)),
            ("eta".to_string(), Number::from(90)),
            ("theta".to_string(), Number::from(105)),
            ("iota".to_string(), Number::from(120)),
            ("kappa".to_string(), Number::from(135)),
            ("lambda".to_string(), Number::from(150)),
            ("mu".to_string(), Number::from(165)),
            ("nu".to_string(), Number::from(180)),
            ("xi".to_string(), Number::from(195)),
            ("omicron".to_string(), Number::from(210)),
            ("pi".to_string(), Number::from(225)),
            ("rho".to_string(), Number::from(240)),
            ("sigma".to_string(), Number::from(255)),
            ("tau".to_string(), Number::from(270)),
            ("upsilon".to_string(), Number::from(285)),
            ("phi".to_string(), Number::from(300)),
            ("chi".to_string(), Number::from(315)),
            ("psi".to_string(), Number::from(330)),
            ("omega".to_string(), Number::from(345)),
        ]),
        light: types::Palette {
            chroma: Number::from_f64(0.70).unwrap(),
            lightness: Number::from_f64(0.25).unwrap(),
            background: types::Color {
                hue: Number::from(0),
                chroma: Number::from_f64(0.0).unwrap(),
                lightness: Number::from_f64(1.0).unwrap(),
            },
            text: types::Color {
                hue: Number::from(0),
                chroma: Number::from_f64(0.0).unwrap(),
                lightness: Number::from_f64(0.0).unwrap(),
            },
        },
        dark: types::Palette {
            chroma: Number::from_f64(0.70).unwrap(),
            lightness: Number::from_f64(0.25).unwrap(),
            background: types::Color {
                hue: Number::from(0),
                chroma: Number::from_f64(0.0).unwrap(),
                lightness: Number::from_f64(0.0).unwrap(),
            },
            text: types::Color {
                hue: Number::from(0),
                chroma: Number::from_f64(0.0).unwrap(),
                lightness: Number::from_f64(1.0).unwrap(),
            },
        },
    },
    mode: types::Mode::System,
    breakpoints: Some(types::BreakpointsConfig {
        viewport: types::ViewportBreakpoints::from([
            (types::Breakpoint::SM, Number::from(600)),
            (types::Breakpoint::MD, Number::from(840)),
            (types::Breakpoint::LG, Number::from(1200)),
            (types::Breakpoint::XL, Number::from(1600)),
            (types::Breakpoint::_2XL, Number::from(1920)),
            (types::Breakpoint::_3XL, Number::from(2560)),
            (types::Breakpoint::_4XL, Number::from(3840)),
        ]),
        container: vec![
            Number::from(10),
            Number::from(20),
            Number::from(30),
            Number::from(40),
            Number::from(50),
            Number::from(60),
            Number::from(70),
            Number::from(80),
            Number::from(90),
            Number::from(100),
            Number::from(200),
            Number::from(300),
            Number::from(400),
            Number::from(500),
            Number::from(600),
            Number::from(700),
            Number::from(800),
            Number::from(900),
            Number::from(1000),
            Number::from(1200),
            Number::from(1400),
            Number::from(1600),
            Number::from(1800),
        ],
    }),
    upscale_from: Some(types::Breakpoint::_2XL),
    spacing: Number::from(1),
    output_dir: Some(String::from("styles")),
});
